# Simulation configuration file


# --- general ---
results_dir: "results/"
data_dir: "data/"
figures_dir: "results/figures/"

# --- sim params ---
nsim: 20000
alpha: 0.05
m: [4, 8, 16, 32, 64]
m0: [0.75, 0.5, 0.25, 0.0]
L: [5, 10]
scheme: ["E", "I", "D"]
rng_seed: 10

methods:
  - Bonferroni
  - BonferroniHochberg
  - BenjaminiHochberg

metrics:
  - Power
  - TrueRejections
  - RejectionsNumber

# -- analysis configuration ---
analyse_scenario:
  - name: power_grid
    x_axis: m
    y_axis: Power
    factors: [method, scheme, m0_fraction]
    se_bands: true
    group_variables: true
  - name: boxplot
    x_axis: scheme
    y_axis: Power
    factors: [method]
  - name: power_ratio_grid
    x_axis: m
    y_axis: Power
    factors: [method, scheme, m0_fraction]
    ratio_variable: L
    group_variables: true


# --- Plotting configuration ---
rcparams:
  text.usetex: true
  font.family: serif
  font.serif: ["Computer Modern Roman"]
  font.size: 9
  figure.titlesize: 11
  legend.fontsize: 10
  legend.title_fontsize: 10.5
  lines.linewidth: 1
  axes.linewidth: 0.5
  axes.facecolor: white
  axes.grid: false
  lines.markersize: 3
  xtick.labelsize: 8
  ytick.labelsize: 8

line_colors:
  "Bonferroni Correction": "#FE6100"
  "Bonferroni-Hochberg Correction": "#DC267F"
  "Benjamini-Hochberg Correction": "#785EF0"

linestyles:
  "Bonferroni Correction": "-"
  "Bonferroni-Hochberg Correction": "--"
  "Benjamini-Hochberg Correction": "-."

name_conversion:
  m: "Number of Tested Hypotheses"
  m0_fraction: "Null"
  scheme: "Testing scheme"
  method: "Multiple testing method"
  Power: "Average Power"
  Power_mean: "Average Power"

plots:
  - name: boxplot
    data_dir: results/raw/boxplot_analysed.csv
    func: plot_boxplot
    x_axis: scheme
    y_axis: Power
    factors: [method, _single_facet]
    height : 4
    n_boxplots : 3
  
  - name: power_grid
    data_dir: results/raw/power_grid_analysed.csv
    func: plot_with_bands
    x_axis: m
    y_axis: Power_mean
    factors: [method, scheme, m0_fraction]
    height : 1.3
    se_bands : Power_sem
    group_variables : true
  
  - name: power_ratio_grid
    data_dir: results/raw/power_ratio_grid_analysed.csv
    func: plot_with_bands
    x_axis: m
    y_axis: Power_ratio
    factors: [method, scheme, m0_fraction]
    height : 1.3
    group_variables : true
    title : "Power Ratio (L=10 / L=5) vs Number of Tested Hypotheses"
    x_axis_title : "Power Ratio (L=10 / L=5)"
    y_axis_title : "Number of Tested Hypotheses"
